openapi: 3.0.1
info:
  title: testMvn
  description: API Definition of testMvn
  version: 1.0.0
servers:
- url: http://localhost:8290/testmvn
paths:
  /:
    get:
      responses:
        default:
          description: Default response
